# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fashion_pb2 as fashion__pb2


class CustomerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCustomer = channel.unary_unary(
                '/fashion.CustomerService/CreateCustomer',
                request_serializer=fashion__pb2.Customer.SerializeToString,
                response_deserializer=fashion__pb2.Customer.FromString,
                )
        self.ReadCustomer = channel.unary_unary(
                '/fashion.CustomerService/ReadCustomer',
                request_serializer=fashion__pb2.CustomerId.SerializeToString,
                response_deserializer=fashion__pb2.Customer.FromString,
                )
        self.UpdateCustomer = channel.unary_unary(
                '/fashion.CustomerService/UpdateCustomer',
                request_serializer=fashion__pb2.Customer.SerializeToString,
                response_deserializer=fashion__pb2.Customer.FromString,
                )
        self.DeleteCustomer = channel.unary_unary(
                '/fashion.CustomerService/DeleteCustomer',
                request_serializer=fashion__pb2.CustomerId.SerializeToString,
                response_deserializer=fashion__pb2.Customer.FromString,
                )
        self.ListCustomers = channel.unary_stream(
                '/fashion.CustomerService/ListCustomers',
                request_serializer=fashion__pb2.Empty.SerializeToString,
                response_deserializer=fashion__pb2.Customer.FromString,
                )


class CustomerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCustomers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCustomer,
                    request_deserializer=fashion__pb2.Customer.FromString,
                    response_serializer=fashion__pb2.Customer.SerializeToString,
            ),
            'ReadCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadCustomer,
                    request_deserializer=fashion__pb2.CustomerId.FromString,
                    response_serializer=fashion__pb2.Customer.SerializeToString,
            ),
            'UpdateCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCustomer,
                    request_deserializer=fashion__pb2.Customer.FromString,
                    response_serializer=fashion__pb2.Customer.SerializeToString,
            ),
            'DeleteCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCustomer,
                    request_deserializer=fashion__pb2.CustomerId.FromString,
                    response_serializer=fashion__pb2.Customer.SerializeToString,
            ),
            'ListCustomers': grpc.unary_stream_rpc_method_handler(
                    servicer.ListCustomers,
                    request_deserializer=fashion__pb2.Empty.FromString,
                    response_serializer=fashion__pb2.Customer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fashion.CustomerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CustomerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fashion.CustomerService/CreateCustomer',
            fashion__pb2.Customer.SerializeToString,
            fashion__pb2.Customer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fashion.CustomerService/ReadCustomer',
            fashion__pb2.CustomerId.SerializeToString,
            fashion__pb2.Customer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fashion.CustomerService/UpdateCustomer',
            fashion__pb2.Customer.SerializeToString,
            fashion__pb2.Customer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fashion.CustomerService/DeleteCustomer',
            fashion__pb2.CustomerId.SerializeToString,
            fashion__pb2.Customer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListCustomers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/fashion.CustomerService/ListCustomers',
            fashion__pb2.Empty.SerializeToString,
            fashion__pb2.Customer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
